CREATE TABLE IF NOT EXISTS users (
 id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email varchar not null unique,
 first_name varchar not null,
last_name varchar not null,
phone varchar not null,
image varchar
);
CREATE TABLE IF NOT EXISTS ads (
                                   pk Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title varchar not null,
                                   image varchar,
                                   price Integer not null,
                                   author Integer,
                                   CONSTRAINT fk_ads_users FOREIGN KEY (author) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS comments (
                                        pk Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created_at timestamp without time zone,
                                        author_image varchar,
                                        author_first_name varchar not null,
                                        text varchar not null,
                                        author Integer,
                                        CONSTRAINT fk_comments_users FOREIGN KEY (author) REFERENCES users (id)
);